version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: login-container
    environment:
      MYSQL_DATABASE: login
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  mysql:
  db_data: